# Generated by Django 5.0.7 on 2024-10-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
