# Generated by Django 5.0.7 on 2024-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_review_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecommonissues',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='machineknowhow',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='machinerareissues',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
