# Generated by Django 5.0.7 on 2024-11-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machinecommonissues_name_machineknowhow_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecommonissues',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common', to='machine.machine'),
        ),
        migrations.AlterField(
            model_name='machineknowhow',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowhow', to='machine.machine'),
        ),
        migrations.AlterField(
            model_name='machinerareissues',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rare', to='machine.machine'),
        ),
        migrations.AlterField(
            model_name='review',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='machine.machine'),
        ),
    ]
