# Generated by Django 5.0.7 on 2024-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_alter_event_options_alter_shift_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
