# Generated by Django 5.0.7 on 2024-07-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_alter_shift_end_date_alter_shift_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
