# Generated by Django 5.0.7 on 2024-07-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_workinghours_shift_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_date',
        ),
    ]
