# Generated by Django 5.0.7 on 2024-07-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_remove_shift_end_date_remove_shift_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='event',
            name='working_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='plan.workinghours'),
        ),
    ]
