# Generated by Django 5.0.7 on 2024-07-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_remove_shift_working_hours_event_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='shift',
            name='working_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='plan.workinghours'),
        ),
    ]
