# Generated by Django 5.0.7 on 2024-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_remove_event_working_hours_shift_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
