# Generated by Django 5.0.7 on 2024-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_event_end_time_event_start_time_alter_event_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
