# Generated by Django 5.0.7 on 2024-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_hourdaycounter_weekendevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='acceptance',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
