# Generated by Django 5.0.7 on 2024-08-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0020_alter_availability_acceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekendevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='weekendevent',
            name='start_time',
        ),
    ]
