# Generated by Django 5.0.7 on 2024-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0022_event_overtime_event_plan_event_date_75f038_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='overtime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
