# Generated by Django 5.0.7 on 2024-11-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0025_alter_holyday_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekendevent',
            name='shift',
        ),
    ]
