# Generated by Django 5.0.7 on 2024-11-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0026_remove_weekendevent_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendevent',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.shift'),
        ),
    ]
